// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1alpha1

// IstioInstallationSlice represents a slice of *IstioInstallation
type IstioInstallationSlice []*IstioInstallation
