// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v1

import (
	proto "github.com/gogo/protobuf/proto"
)

// DeepCopyInto for the AuthConfig.Spec
func (in *AuthConfigSpec) DeepCopyInto(out *AuthConfigSpec) {
	p := proto.Clone(in).(*AuthConfigSpec)
	*out = *p
}

// DeepCopyInto for the AuthConfig.Status
func (in *AuthConfigStatus) DeepCopyInto(out *AuthConfigStatus) {
	p := proto.Clone(in).(*AuthConfigStatus)
	*out = *p
}

// DeepCopyInto for the Settings.Spec
func (in *SettingsSpec) DeepCopyInto(out *SettingsSpec) {
	p := proto.Clone(in).(*SettingsSpec)
	*out = *p
}

// DeepCopyInto for the Upstream.Spec
func (in *UpstreamSpec) DeepCopyInto(out *UpstreamSpec) {
	p := proto.Clone(in).(*UpstreamSpec)
	*out = *p
}

// DeepCopyInto for the Upstream.Status
func (in *UpstreamStatus) DeepCopyInto(out *UpstreamStatus) {
	p := proto.Clone(in).(*UpstreamStatus)
	*out = *p
}

// DeepCopyInto for the UpstreamGroup.Spec
func (in *UpstreamGroupSpec) DeepCopyInto(out *UpstreamGroupSpec) {
	p := proto.Clone(in).(*UpstreamGroupSpec)
	*out = *p
}

// DeepCopyInto for the UpstreamGroup.Status
func (in *UpstreamGroupStatus) DeepCopyInto(out *UpstreamGroupStatus) {
	p := proto.Clone(in).(*UpstreamGroupStatus)
	*out = *p
}

// DeepCopyInto for the Proxy.Spec
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	p := proto.Clone(in).(*ProxySpec)
	*out = *p
}

// DeepCopyInto for the Proxy.Status
func (in *ProxyStatus) DeepCopyInto(out *ProxyStatus) {
	p := proto.Clone(in).(*ProxyStatus)
	*out = *p
}
