// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/solo-apis/api/gloo-fed/fed.rpc/v1/common.proto

// defines common types shared across DevPortal component APIs

package v1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for ObjectMeta
func (this *ObjectMeta) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ObjectMeta
func (this *ObjectMeta) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Time
func (this *Time) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Time
func (this *Time) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ResourceYaml
func (this *ResourceYaml) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ResourceYaml
func (this *ResourceYaml) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CommonMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	CommonUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
