// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v2

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto for the ExternalService.Spec
func (in *ExternalServiceSpec) DeepCopyInto(out *ExternalServiceSpec) {
	p := proto.Clone(in).(*ExternalServiceSpec)
	*out = *p
}

// DeepCopyInto for the ExternalService.Status
func (in *ExternalServiceStatus) DeepCopyInto(out *ExternalServiceStatus) {
	p := proto.Clone(in).(*ExternalServiceStatus)
	*out = *p
}

// DeepCopyInto for the ExternalEndpoint.Spec
func (in *ExternalEndpointSpec) DeepCopyInto(out *ExternalEndpointSpec) {
	p := proto.Clone(in).(*ExternalEndpointSpec)
	*out = *p
}

// DeepCopyInto for the ExternalEndpoint.Status
func (in *ExternalEndpointStatus) DeepCopyInto(out *ExternalEndpointStatus) {
	p := proto.Clone(in).(*ExternalEndpointStatus)
	*out = *p
}

// DeepCopyInto for the RouteTable.Spec
func (in *RouteTableSpec) DeepCopyInto(out *RouteTableSpec) {
	p := proto.Clone(in).(*RouteTableSpec)
	*out = *p
}

// DeepCopyInto for the RouteTable.Status
func (in *RouteTableStatus) DeepCopyInto(out *RouteTableStatus) {
	p := proto.Clone(in).(*RouteTableStatus)
	*out = *p
}

// DeepCopyInto for the VirtualDestination.Spec
func (in *VirtualDestinationSpec) DeepCopyInto(out *VirtualDestinationSpec) {
	p := proto.Clone(in).(*VirtualDestinationSpec)
	*out = *p
}

// DeepCopyInto for the VirtualDestination.Status
func (in *VirtualDestinationStatus) DeepCopyInto(out *VirtualDestinationStatus) {
	p := proto.Clone(in).(*VirtualDestinationStatus)
	*out = *p
}

// DeepCopyInto for the VirtualGateway.Spec
func (in *VirtualGatewaySpec) DeepCopyInto(out *VirtualGatewaySpec) {
	p := proto.Clone(in).(*VirtualGatewaySpec)
	*out = *p
}

// DeepCopyInto for the VirtualGateway.Status
func (in *VirtualGatewayStatus) DeepCopyInto(out *VirtualGatewayStatus) {
	p := proto.Clone(in).(*VirtualGatewayStatus)
	*out = *p
}
