// Code generated by skv2. DO NOT EDIT.

// Package v1 contains API Schema definitions for the settings.solo.io v1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=settings.solo.io
package v1
