name: Tag Commit on LTS Branch
on:
  push:
    branches:
      - main
      - 'gloo-main'
      - 'gloo-v**.**.x'
jobs:
  tag-version:
    runs-on: ubuntu-latest
    env:
      # The regex of a commit produced by the soloio-bot
      COMMIT_REGEX: "^.*(Sync APIs.)+.*$"
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Parse out tag name from commit message
        id: tag_version
        run: |
          if [[ $(git log -1 --oneline) =~ ${{ env.COMMIT_REGEX }} ]]; then
            TAG_NAME=$(git log -1 --oneline | awk -F'@tag-name=' '{print $2}' | awk -F' ' '{print $1}')
          fi
          echo "tag_name=$(echo $TAG_NAME)" >> $GITHUB_OUTPUT
      - name: Bump version and push tag
        if: steps.tag_version.outputs.tag_name != ''
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.tag_version.outputs.tag_name }}
          RELEASE_BRANCHES: '.*main$,gloo-v[0-9]+\.[0-9]+\.x$'
