name: Tag Commit on gloo-repo-branch Branch
on:
  push:
    branches:
      - gloo-repo-branch
jobs:
  tag-version:
    runs-on: ubuntu-latest
    env:
      # The regex of a commit produced by the soloio-bot
      COMMIT_REGEX: "^.*(Solo APIs.)+.*$"
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Parse out tag name from commit message
        id: tag_version
        run: |
          if [[ $(git log -1 --oneline) =~ ${{ env.COMMIT_REGEX }} ]]; then
            TAG_NAME=$(git log -1 --oneline | awk -F'@tag-name=' '{print $2}' | awk -F' ' '{print $1}')
          fi
          echo "::set-output name=tag_name::$(echo $TAG_NAME)"
      - name: Bump version and push tag
        if: steps.tag_version.outputs.tag_name != ''
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: solo-apis-${{ steps.tag_version.outputs.tag_name }}
          RELEASE_BRANCHES: gloo-repo-branch
