name: pull_request

on:
  pull_request:

jobs:
  gen:
    name: Code Gen
    runs-on: ubuntu-22.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go 1.14
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
      id: go
    - name: Install Protoc
      uses: arduino/setup-protoc@master
      with:
        version: '3.6.1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Code
      run: |
        ./ci/check-code-gen.sh

  test:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Private Repo Permissions
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global url."https://${TOKEN}@github.com/solo-io/".insteadOf "https://github.com/solo-io/"
      - name: Set up Go 1.14
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Run tests
        run: |
          go test ./test/scripts/...