name: tag version
on:
  push:
    branches:
      - master
      - gloo-v**.**.x
jobs:
  tag-version:
    runs-on: ubuntu-latest
    env:
      # The regex of a commit produced by the soloio-bot
      COMMIT_REGEX: "^.*(@soloio-bot Sync Gloo APIs.)+.*$"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Parse out tag name from commit message
        id: tag_version
        shell: bash "{0}"
        run: |
          if [[ $(git log -1 --oneline) =~ $ {{ env.COMMIT_REGEX }} ]]; then
            TAG_NAME=$(git log -1 --oneline | cut -d "@tag-name=" -f 2)
          fi
          echo "::set-output name=tag_name::$(echo $TAG_NAME)"
      - name: Bump version and push tag
        if: steps.tag_version.outputs.tag_name != ''
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.tag_version.outputs.tag_name }}